---
language: c
test_env: google_test
analysis_dirs:
  - src
  - include
include_dirs:
  - include
build_script:
  log: true
  linux:
    - rm -rf build
    - mkdir build
    - cd build
    - cmake ..
    - make
libs:
  - build/libc_example.so
tlg:
  prefix: |
    #ifdef __cplusplus
    extern "C" {
    #endif
  suffix: |
    #ifdef __cplusplus
    }
    #endif
