---
language: rust

rust:
  - stable
  - beta
  - nightly

dist: trusty

matrix:
  allow_failures:
    - rust: nightly

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
    - secure: "P0Ue2XFC+FJhIxAo7mCl5GRlFIRb6oyTdP0yt8fiz2a5cLru9ohomaHzjxTERnvBkMpAeRPRN9HaExgd0/2jkDCy2hGUHyj8U58XBF90mwvIqeg6CnMFQ/YRawQ5vWQ5Q/x4lcY+J6bJzkT9nf+FVY6IOr2gEJiQj1lzWTgmFC4kRbqY5DHwIeiQKPbZj66t5zU4lzo3OaVh7SZhtxYZ8Ccr7kELg90LHUPVmmA453vkEnVk6ZGHPSSKIdi+CAt0VGaF+drquSrOXdDy7/5mHh+J9IiHHe0UCr1fYNuY05iSBiAmTvOXuB4ebfdl/1///qksjG/TesrF6NHEpVoMQzOu1UCB4o7n4B7klzngspxNq0RRvG7Df1D4BYIrk1mZoNDNqkHchZAicyMkmwDQIscIe8IpJupZLt1Vvsgu/2zI/ovpOnkBkvwXjYtipDhtvmI2IwT2BAORcV+/I12kgITlHhRF+GdCPY5uhhNDYmnOYproclenfyKaP0Ojzd/jZtGlULtZsqMSB0XEl6Y84VGHrqZtiHWHYsTc0vAIDYSTjbUFw/ZTWy7peTBgrsqaGWrboevbyTxUxcHzawEbs8Oz0JpZnvPapU9WKFinJYCBNY0HHQIWA8iyzgsatnVDRRji1RInl0o5WGShxr50JIhd0NDk/ZusW2prFifU794="
  matrix:
    - LLVM_VERSION=4.0 CLANG_VERSION=clang_4_0
    - LLVM_VERSION=5.0 CLANG_VERSION=clang_5_0

cache:
  cargo: true
  apt: true
  directories:
    - $HOME/.cargo
    - $HOME/.llvm

os:
  - linux
  - osx

before_install: . ./ci/before_install.sh
before_script: . ./ci/before_script.sh
script: . ./ci/script.sh
after_success: . ./ci/after_success.sh

notifications:
  email:
    on_success: never
