---
language: rust

rust:
  - stable
  - beta
  - nightly

sudo: required
dist: trusty

matrix:
  allow_failures:
    - rust: nightly

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - libssl-dev
      - zlib1g-dev

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
    - secure: "P0Ue2XFC+FJhIxAo7mCl5GRlFIRb6oyTdP0yt8fiz2a5cLru9ohomaHzjxTERnvBkMpAeRPRN9HaExgd0/2jkDCy2hGUHyj8U58XBF90mwvIqeg6CnMFQ/YRawQ5vWQ5Q/x4lcY+J6bJzkT9nf+FVY6IOr2gEJiQj1lzWTgmFC4kRbqY5DHwIeiQKPbZj66t5zU4lzo3OaVh7SZhtxYZ8Ccr7kELg90LHUPVmmA453vkEnVk6ZGHPSSKIdi+CAt0VGaF+drquSrOXdDy7/5mHh+J9IiHHe0UCr1fYNuY05iSBiAmTvOXuB4ebfdl/1///qksjG/TesrF6NHEpVoMQzOu1UCB4o7n4B7klzngspxNq0RRvG7Df1D4BYIrk1mZoNDNqkHchZAicyMkmwDQIscIe8IpJupZLt1Vvsgu/2zI/ovpOnkBkvwXjYtipDhtvmI2IwT2BAORcV+/I12kgITlHhRF+GdCPY5uhhNDYmnOYproclenfyKaP0Ojzd/jZtGlULtZsqMSB0XEl6Y84VGHrqZtiHWHYsTc0vAIDYSTjbUFw/ZTWy7peTBgrsqaGWrboevbyTxUxcHzawEbs8Oz0JpZnvPapU9WKFinJYCBNY0HHQIWA8iyzgsatnVDRRji1RInl0o5WGShxr50JIhd0NDk/ZusW2prFifU794="
  matrix:
    - LLVM_VERSION=5.0 CLANG_VERSION=clang_5_0
    - LLVM_VERSION=6.0 CLANG_VERSION=clang_6_0

cache:
  apt: true
  directories:
    - $HOME/.llvm

os:
  - linux

before_install: . ./ci/install.sh

before_script:
  - pip install 'travis-cargo<0.2' --user --verbose
  - export PATH=$HOME/.local/bin:$PATH
  - export PATH=$HOME/Library/Python/2.7/bin:$PATH

script:
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then rvm get head || true; fi
  - if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]] && [[ "$TRAVIS_OS_NAME" == "linux" ]]; then CLANG_VERSION="$CLANG_VERSION clippy"; fi
  - RUST_BACKTRACE=1 cargo test --verbose --features $CLANG_VERSION -- --nocapture
  - cargo doc --no-deps

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == "stable" ]] && [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    travis-cargo doc-upload
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi

notifications:
  email:
    on_success: never
