/*****************************************************************************/
/**
 ** \file       tlg.h
 ** \brief      This is a general header for unittest includes.
 **             It is autogenerated by the thinline project. Do not modify
 **             unless you know what you're doing.
 **/
/*****************************************************************************/

#ifndef ___TLG_H___
#define ___TLG_H___

// USER_SPECIFIC_PREFIX_CONTENT //
// INCLUDES //

// USER_SPECIFIC_SUFFIX_CONTENT //

#endif //___TLG_H___
